name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt-get install wget build-essential python3 verilator libevent-dev libjson-c-dev device-tree-compiler
          pip3 install setuptools
          pip3 install requests
          pip3 install pexpect
          pip3 install meson
          pip3 install ninja

      # Install (n)Migen / LiteX / Cores
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py init install --user

      # Install RISC-V GCC
      - name: Install RISC-V GCC
        run: |
          wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14.tar.gz
          tar -xf $PWD/riscv64-*.tar.gz
          sudo mkdir /usr/local/riscv
          sudo cp -r $PWD/riscv64-*/* /usr/local/riscv

      # Test
      - name: Run Tests
        run: |
          export PATH=/usr/local/riscv/bin:$PATH
          python3 -m unittest test.test_build
